### PR TITLE
Update editUser() to use a PS instead of a string to build out the query 

### PR DESCRIPTION
**Pull request by ppatel9703**

### CODE REVIEW

**Comment by themaherkhalil** [comment]
Anyway we can undo the updates regarding to the formatting of the file? The diff is so large it is hard to know what code was actually changed

**Comment by ppatel9703** [comment]
Yeah i see what you are saying, let me try to get to it prior to that push and apply just my changes-- give me a few to test it out

**Comment by ppatel9703** [comment]
Can't rollback/cherrypick to a commit prior to that change-- @themaherkhalil I can make a new branch and delete this one since its a one function change. Would you prefer that?

**Comment by themaherkhalil** [comment]
I copied the single method, did a git checkout origin/dev filename to revert the one file to the latest dev, then i added back the method change to get it back so its just the one method that shows up as a diff.

**Comment by themaherkhalil** [comment]
In terms of the patch, we need to actually do the ps.setString(), ps.setBoolean(), etc. etc. with regards to the values of the update statement. 

The issue is when the database is something like MS Sql Server, it is not SQL set <columnname>=true it has to be <columnname>='true' (quotes around the value).  That is why we need to shift to using a prepared statement since ps.setBoolean handles that for us.

**Pull request merged**
